### ISSUE TITLE
simple demo launch rviz error

### ISSUE THREAD

**Issue by KMU-VI-kahn** [ANYbotics/grid_map#269] opened 2020-11-09 16:45 UTC
I build from the source code successly,but when I run :
$roslaunch grid_map_demos simple_demo.launch
It shows:

[rviz-3] process has died [pid 12804, exit code -11, cmd /opt/ros/melodic/lib/rviz/rviz -d /home/kahn/kahn_ros_ws/src/grid_map/grid_map_demos/rviz/grid_map_demo.rviz __name:=rviz __log:=/home/kahn/.ros/log/8c65ba5e-22a9-11eb-8d8c-1c1b0dc1bb12/rviz-3.log].

![스크린샷, 2020-11-10 01-36-36](https://user-images.githubusercontent.com/34730642/98569160-48e17880-22f5-11eb-83a1-2808f78f39ca.png)

I want to know if the grid map package is available in ubuntu 18.04 and ros melodic environment.

**Comment by maximilianwulf** [comment] 2020-11-11 11:30
Hey @KMU-VI-kahn thank you for the issue. This is a duplicate of https://github.com/ANYbotics/grid_map/issues/267, please refer to it for a future solution.

**Closed by maximilianwulf** 2020-11-11 11:30 UTC
